# Generated by Django 4.2.16 on 2024-11-10 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=30)),
                ('room_available', models.BooleanField(default=True)),
                ('room_price', models.FloatField()),
                ('room_purpose', models.TextField(choices=[('accomodation', 'accomodation'), ('meeting', 'meeting'), ('conference', 'conference')], default='accomodation')),
                ('room_capacity', models.PositiveIntegerField()),
                ('room_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('payable', models.BooleanField(default=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookroom.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
